<?php

/**
 * Implements hook_form_alter().
 */
function campuscms_register_people_cleanup_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  if (!in_array('administrator', $user->roles)) {
    if ($form_id == 'user_register_form') {
      $form['account']['name']['#title'] = t('E-mail Address');
      $form['account']['cas_name']['#access'] = FALSE;
      $form['account']['mail']['#access'] = FALSE;
      $form['account']['status']['#access'] = FALSE;
      array_unshift($form['#validate'], 'campuscms_register_people_cleanup_user_register_validate');
    }
    elseif ($form_id == 'user_profile_form') {
      if (!empty($form['account']['cas_name']['#default_value'])) {
        $form['account']['current_pass']['#access'] = FALSE;
        $form['account']['pass']['#access'] = FALSE;
      }
      else {
        $form['account']['name']['#title'] = t('E-mail Address');
      }

      $form['account']['cas_name']['#access'] = FALSE;
      $form['account']['mail']['#access'] = FALSE;
      $form['account']['status']['#access'] = FALSE;
    }
  }
}

function campuscms_register_people_cleanup_user_register_validate(&$form, &$form_state) {
  if (empty($form_state['values']['cas_name']) && valid_email_address($form_state['values']['name'])) {
    $form_state['values']['mail'] = $form_state['values']['name'];
  }
}

/**
 * Implements hook_menu_alter().
 */
function campuscms_register_people_cleanup_menu_alter(&$items) {
  $items['admin/people/cas/create']['access arguments'] = array('administer cas');
  $items['user/%user/cas']['access arguments'] = array('administer cas');
  $items['user/%user/cas/delete']['access arguments'] = array('administer cas');
}
